version: '3'
services:
  app:
    build: .
    tty: true
    stdin_open: true
    command: /bin/bash
    volumes:
      - ../cmd:/go/src/work
    depends_on:
      - db
  db:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports: 
      - '33307:3307'
    expose: 
      - '3307'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: "Asia/Tokyo"
    volumes:
      - ../db/conf:/etc/mysql/conf.d
      - ../db/init:/docker-entrypoint-initdb.d